export enum ENV {
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_REFRESH_LIFETIME,
  PORT,
  JWT_ACCESS_LIFETIME, // 15 minutes
  JWT_REFRESH_COOKIE,
  NODE_ENV,
  HOST,
  PG_USER,
  PG_DB,
  PG_PWD,
  PG_HOST,
  PG_PORT,
}
